services:
  jij-mcp-server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
    image: ghcr.io/jij-inc/jij-mcp-server:${GIT_BRANCH:-latest}
